// Driver CHATROOMS
export const GET_CHATROOMS = "GET_CHATROOMS";
export const ADD_CHATROOMS = "ADD_CHATROOMS";
export const CHATROOMS_LOADING = "CHATROOMS_LOADING";

// Driver Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const Delete_Account = "DELETE_ACCOUNT";
export const DRIVER_LOCATION = "DRIVER_LOCATION";
export const LOCATION_LOADING = "LOCATION_LOADING";

// Journey
// Driver CHATROOMS
export const GET_JOURNEYS = "GET_JOURNEYS";
export const JOURNEY_LOADING = "JOURNEY_LOADING";
export const ADD_JOURNEY = "ADD_JOURNEY";
export const JOURNEY_FAIL = "JOURNEY_FAIL";
export const UPDATE_JOURNEY = "UPDATE_JOURNEY";
export const DELETE_JOURNEY = "DELETE_JOURNEY";
